# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 431)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFileButton.setGeometry(QtCore.QRect(200, 20, 89, 25))
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.inputFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputFilePath.setGeometry(QtCore.QRect(20, 20, 171, 25))
        self.inputFilePath.setReadOnly(True)
        self.inputFilePath.setObjectName("inputFilePath")
        self.convertFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertFileButton.setGeometry(QtCore.QRect(10, 130, 89, 25))
        self.convertFileButton.setObjectName("convertFileButton")
        self.logText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logText.setGeometry(QtCore.QRect(0, 220, 541, 161))
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.deviceLabel = QtWidgets.QLabel(self.centralwidget)
        self.deviceLabel.setGeometry(QtCore.QRect(20, 60, 67, 21))
        self.deviceLabel.setObjectName("deviceLabel")
        self.deviceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.deviceComboBox.setGeometry(QtCore.QRect(80, 60, 131, 21))
        self.deviceComboBox.setObjectName("deviceComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseFileButton.setText(_translate("MainWindow", "Choose file"))
        self.inputFilePath.setPlaceholderText(_translate("MainWindow", "File path"))
        self.convertFileButton.setText(_translate("MainWindow", "Convert"))
        self.logText.setPlaceholderText(_translate("MainWindow", "Log..."))
        self.deviceLabel.setText(_translate("MainWindow", "Device:"))
